version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t footballjourneys:latest .
      - docker tag footballjourneys:latest 864981742740.dkr.ecr.us-east-2.amazonaws.com/footballjourneys:latest
      - docker push 864981742740.dkr.ecr.us-east-2.amazonaws.com/footballjourneys:latest